spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swTodo
    username: root
    password: hjkas1541

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    properties:
      hibernate:
        format_sql: 'true'

    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
