spring:
  datasource:
    url: jdbc:mysql://database-1.c3375gesjkvq.ap-northeast-2.rds.amazonaws.com/swTodo
    username: admin
    password: asdfasdf

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    properties:
      hibernate:
        format_sql: 'true'

    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


springdoc:
  swagger-ui:
    enabled: true # swagger ui 사용여부 (굳이 설정하지 않아도 default는 true)
  version: 'v1' # API 문서 버전
  default-consumes-media-type: application/json #기본 consume media type
  default-produces-media-type: application/json # 기본 produce media type
  model-and-view-allowed: true # ModelAndView 허용
  packages-to-scan: com.example.swbackend
